% This function mxNiUpdateContext, waits for the Kinect or stream Movie
%   to update all nodes, to the next frame
%
% 	mxNiUpdateContext(KinectHandles);
%
% inputs,
%   KinectHandles : Array with pointers to kinect node objects generated by
%          mxNiCreateContext, such as main, image, IR, Depth and User node.
%
%
% See also mxNiCreateContext, mxNiDepth, mxNiPhoto, mxNiDepthRealWorld
%		mxNiInfrared, mxNiSkeleton, mxNiDeleteContext
%
% Mex-Wrapper is written by D.Kroon University of Twente (February 2011)  